image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp index.html 404.html
    - mv build public
  artifacts:
    paths:
      - public